---
title: "Arbeidskrav"
format: pdf
editor: visual
---

## Arbeidskrav 2

```{r}
library(tidyverse)
library(rvest)  
library(janitor) 
library(lubridate) 
library(quantmod) 
library(ggplot2)
```

```{r}
url <- "https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132"

url <- url %>%
   read_html() %>% 
   html_nodes("table") %>%  
   html_table() %>% .[[1]]  %>% head(34)
names(url) <- c("Modell (temp. varierte fra 0° til -10°)", "WLTP-tall", "STOPP", "Avvik")
```

```{r}
table <- url %>%
  select(c("Modell (temp. varierte fra 0° til -10°)", "WLTP-tall", "STOPP"))
```

```{r}
table$STOPP <- gsub("x", "", table$STOPP)
```

```{r}
table$STOPP <- gsub("STOPP", "", table$STOPP)
table$`WLTP-tall` <- gsub("WLTP-tall", "", table$`WLTP-tall`)
```

```{r}
table <- table %>%
  separate('WLTP-tall', into=c("WLTP-km", "WLTP-kwh"), sep="/") %>%
  separate("WLTP-km", into = "WLTP-km", sep=" ") %>%
  separate("STOPP", into=c("STOPP-km"), sep=" ")
```

```{r}
table$`STOPP-km` <- as.numeric(table$`STOPP-km`)
table$`WLTP-km` <- as.numeric(table$`WLTP-km`)
```

```{r}

table  %>%
  ggplot(aes(x=`WLTP-km`, y=`STOPP-km`))+
  geom_point(col="blue") +
  ggtitle("Forholdet mellom WLTP-tall og STOPP")+
plot(table)                         
abline(coef = c(0, 1),
       col = "red",
       lwd = 1.5)
  


# kode hentet fra: https://statisticsglobe.com/add-diagonal-line-plot-r
```

Ved å se på grafen kan vi se at det er store avvike, på hvor langt bilene skulle gå, og hvor langt den endte opp med å gå. Vi ser at de fleste bilene stoppet før, enn forventet lengde bilden skulle kunne gå. Dette gjelder altså de fleste bilene.

```{r}
 
lm(`STOPP-km` ~ `WLTP-km`, data = table)
```

Tallene forteller noe om hvor store avvikene er tilsammen.

```{r}
lm(`STOPP-km` ~ `WLTP-km`, data = table) + geom_smooth(method = lm)
```
